# fly.toml app configuration file generated for dm-multiplayer on 2024-06-27T22:26:05+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dm-multiplayer'
primary_region = 'lhr'

[build]
  [build.args]
    GO_VERSION = '1.21.3'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
